// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CrossBase.CodeGeneration.Templates
{
    using System.Collections.Generic;
    using Language;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class DispatchProxyTemplate : Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 5 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

    public string ClassName;
	public string ProxyName;
	public string InterfaceName;
	public string ProxyNamespace;
	public List<string> CustomDefaultNamespaces;
    private string attributeName;

    public override void Render()
	{
		debugOutput = string.Empty;
        attributeName = "DispatchProxy";
        var classes = Parser.GetAllClassesThatHaveAnAttribute(attributeName);

		foreach (var @class in classes)
		{
			foreach(var attribute in @class.Attributes)
			{
				if (attribute.Name != attributeName)
					continue; 
						
				ProxyName = @class.Name;
				ProxyNamespace = @class.Namespace.Name;
				InterfaceName = attribute.GetArgument("InterfaceName");
				ClassName = attribute.GetArgument("ClassName");
				
				var fileName = attribute.FileName;
				var projectItem = Parser.GetProjectItem(fileName);
				var outputFileName = fileName.Replace(".cs", "." + InterfaceName + "." + attributeName + ".g.cs");

				if (string.IsNullOrEmpty(InterfaceName))
				{
					debugOutput += string.Format("InterfaceName not set on " + attributeName + " attribute on class {0}\r\n", @class.Name);		
					continue;
				}

				var @interface = Parser.Interfaces.Find(f=> f.Name == InterfaceName);
				if (@interface == null)
				{
					debugOutput += string.Format("Interface {1} not found " + attributeName + " attribute on class {0}\r\n", @class.Name, InterfaceName);		
					continue;
				}

			    var useDefaultRule = false;
				if (string.IsNullOrEmpty(ClassName))
				{
					debugOutput += string.Format("ClassName to proxy not set on " + attributeName + " attribute on class {0}, using default name derived from interface name\r\n", @class.Name);
				    useDefaultRule = true;
				}


				var fieldName =  useDefaultRule ? @interface.GetDefaultPrivateFieldName() : ClassName.ChangeFirstChar(ChangeCase.ToLower);
				var propertyName = useDefaultRule? @interface.GetDefaultPropertyName() : ClassName;


			    var containsNotifyPropertyChanged = @interface.AllEvents.Exists(s => s.Name == "PropertyChanged");

				GenerateHeader();
			    var usings = new List<string>
			        {
			            "System",
			            "CrossBase.Dispatch",
			            "CrossBase.Serialization",
			        };
				if (containsNotifyPropertyChanged)
					usings.Add("System.ComponentModel");
				GenerateUsings(@class, usings);

        
        #line default
        #line hidden
        
        #line 72 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("using ");

        
        #line default
        #line hidden
        
        #line 73 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(@interface.Namespace.Name));

        
        #line default
        #line hidden
        
        #line 73 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n\r\nnamespace ");

        
        #line default
        #line hidden
        
        #line 75 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ProxyNamespace));

        
        #line default
        #line hidden
        
        #line 75 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\r\n{\r\n\tpublic interface I");

        
        #line default
        #line hidden
        
        #line 77 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ProxyName));

        
        #line default
        #line hidden
        
        #line 77 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" \r\n\t{\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 79 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(@interface.Name));

        
        #line default
        #line hidden
        
        #line 79 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 79 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));

        
        #line default
        #line hidden
        
        #line 79 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" { get; set; }\r\n\t\tIDispatcher UpDispatcher { get; set; }\r\n        IDispatcher Dow" +
        "nDispatcher { get; set; }\r\n");

        
        #line default
        #line hidden
        
        #line 82 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
			foreach (var function in @interface.AllFunctions)
				{
        
        #line default
        #line hidden
        
        #line 83 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\tevent EventHandler<EventArgs> ");

        
        #line default
        #line hidden
        
        #line 84 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 84 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Started;\r\n\t\tevent EventHandler<EventArgs> ");

        
        #line default
        #line hidden
        
        #line 85 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 85 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Finished;\r\n");

        
        #line default
        #line hidden
        
        #line 86 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				}

				foreach (var prop in @interface.AllProperties)
				{ 
        
        #line default
        #line hidden
        
        #line 90 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 91 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Type));

        
        #line default
        #line hidden
        
        #line 91 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 91 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));

        
        #line default
        #line hidden
        
        #line 91 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Invoke { get; set; } \r\n");

        
        #line default
        #line hidden
        
        #line 92 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

					if (containsNotifyPropertyChanged)
					{
        
        #line default
        #line hidden
        
        #line 94 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 95 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Type));

        
        #line default
        #line hidden
        
        #line 95 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 95 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));

        
        #line default
        #line hidden
        
        #line 95 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("BeginInvoke { get; set; } \r\n");

        
        #line default
        #line hidden
        
        #line 96 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

					}
				}

				foreach (var func in @interface.AllFunctions)
				{ 
					if (func.Type == "void")
					{
        
        #line default
        #line hidden
        
        #line 103 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 104 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(func.InterfaceSignature(string.Empty, "BeginInvoke")));

        
        #line default
        #line hidden
        
        #line 104 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 105 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
					    
					}
        
        #line default
        #line hidden
        
        #line 106 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 107 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(func.InterfaceSignature(string.Empty, "Invoke")));

        
        #line default
        #line hidden
        
        #line 107 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 108 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				}

        
        #line default
        #line hidden
        
        #line 110 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t}\r\n\r\n\tpublic partial class ");

        
        #line default
        #line hidden
        
        #line 113 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ProxyName));

        
        #line default
        #line hidden
        
        #line 113 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(": I");

        
        #line default
        #line hidden
        
        #line 113 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ProxyName));

        
        #line default
        #line hidden
        
        #line 113 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 113 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
 if (containsNotifyPropertyChanged){
        
        #line default
        #line hidden
        
        #line 113 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(", INotifyPropertyChanged");

        
        #line default
        #line hidden
        
        #line 113 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
}
        
        #line default
        #line hidden
        
        #line 113 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\r\n\t{\r\n\t\tpublic IDispatcher UpDispatcher { get; set; }\r\n        public IDispatcher" +
        " DownDispatcher { get; set; }\r\n        \r\n");

        
        #line default
        #line hidden
        
        #line 119 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
				foreach (var evnt in @interface.AllEvents)
				{
        
        #line default
        #line hidden
        
        #line 120 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\tpublic event ");

        
        #line default
        #line hidden
        
        #line 121 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.Type));

        
        #line default
        #line hidden
        
        #line 121 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 121 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.Name));

        
        #line default
        #line hidden
        
        #line 121 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 122 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				}

        
        #line default
        #line hidden
        
        #line 125 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				foreach (var prop in @interface.AllProperties)
				{ 
					if (containsNotifyPropertyChanged)
					{
        
        #line default
        #line hidden
        
        #line 129 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\tprivate ");

        
        #line default
        #line hidden
        
        #line 130 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Type));

        
        #line default
        #line hidden
        
        #line 130 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 130 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.GetDefaultPrivateFieldName()));

        
        #line default
        #line hidden
        
        #line 130 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("BeginInvoke;\r\n\t\tpublic ");

        
        #line default
        #line hidden
        
        #line 131 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Type));

        
        #line default
        #line hidden
        
        #line 131 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 131 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));

        
        #line default
        #line hidden
        
        #line 131 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("BeginInvoke \r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn ");

        
        #line default
        #line hidden
        
        #line 135 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.GetDefaultPrivateFieldName()));

        
        #line default
        #line hidden
        
        #line 135 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n\t\t\t}\r\n\t\t\tset\r\n\t\t\t{\r\n\t\t\t\tif (value is ICloneable)\r\n\t\t\t\t{\r\n\t\t\t\t\tvalue = (");

        
        #line default
        #line hidden
        
        #line 141 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Type));

        
        #line default
        #line hidden
        
        #line 141 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(")(clone as ICloneable).Clone();\r\n\t\t\t\t}\r\n\t\t\t\tDownDispatcher.BeginInvoke(() => \r\n\t\t" +
        "\t\t{\r\n\t\t\t\t\tif (value == ");

        
        #line default
        #line hidden
        
        #line 145 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 145 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 145 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));

        
        #line default
        #line hidden
        
        #line 145 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(")\r\n\t\t\t\t\t\treturn;\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 147 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 147 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 147 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));

        
        #line default
        #line hidden
        
        #line 147 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" = value; \r\n\t\t\t\t});\r\n\r\n\t\t\t}\r\n\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 152 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				    }
					else
					{
        
        #line default
        #line hidden
        
        #line 155 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\tprivate ");

        
        #line default
        #line hidden
        
        #line 156 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Type));

        
        #line default
        #line hidden
        
        #line 156 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 156 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.GetDefaultPrivateFieldName()));

        
        #line default
        #line hidden
        
        #line 156 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Invoke;\r\n\r\n\t\tpublic ");

        
        #line default
        #line hidden
        
        #line 158 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Type));

        
        #line default
        #line hidden
        
        #line 158 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 158 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));

        
        #line default
        #line hidden
        
        #line 158 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Invoke \r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\tvar value = ");

        
        #line default
        #line hidden
        
        #line 162 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.GetDefaultPrivateFieldName()));

        
        #line default
        #line hidden
        
        #line 162 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Invoke;\r\n\t\t\t\tDownDispatcher.Invoke(() => \r\n\t\t\t\t{\r\n\t\t\t\t\tvalue = ");

        
        #line default
        #line hidden
        
        #line 165 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 165 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 165 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));

        
        #line default
        #line hidden
        
        #line 165 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n\t\t\t\t\tif (value is ICloneable)\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tvalue = (");

        
        #line default
        #line hidden
        
        #line 168 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Type));

        
        #line default
        #line hidden
        
        #line 168 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(")(value as ICloneable).Clone();\r\n\t\t\t\t\t}\t\t\t\t\t \r\n\t\t\t\t});\r\n\t\t\t\treturn value;\r\n\t\t\t}\r\n" +
        "\t\t\tset\r\n\t\t\t{\r\n\t\t\t\tif (value is ICloneable)\r\n\t\t\t\t{\r\n\t\t\t\t\tvalue = (");

        
        #line default
        #line hidden
        
        #line 177 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Type));

        
        #line default
        #line hidden
        
        #line 177 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(")(value as ICloneable).Clone();\r\n\t\t\t\t}\r\n\t\t\t\tDownDispatcher.Invoke(() => \r\n\t\t\t\t{\r\n" +
        "\t\t\t\t\tif (value == ");

        
        #line default
        #line hidden
        
        #line 181 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 181 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 181 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));

        
        #line default
        #line hidden
        
        #line 181 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(")\r\n\t\t\t\t\t\treturn;\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 183 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 183 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 183 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));

        
        #line default
        #line hidden
        
        #line 183 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" = value; \r\n\t\t\t\t});\r\n\t\t\t}\r\n\t\t}\t\t\t\t    \r\n");

        
        #line default
        #line hidden
        
        #line 187 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
					}
				}
				foreach (var function in @interface.AllFunctions)
				{
        
        #line default
        #line hidden
        
        #line 190 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\tpublic event EventHandler<EventArgs> ");

        
        #line default
        #line hidden
        
        #line 191 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 191 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Started;\r\n\t\tpublic event EventHandler<EventArgs> ");

        
        #line default
        #line hidden
        
        #line 192 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 192 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Finished;\r\n\t\t\r\n\t\tprivate void Invoke");

        
        #line default
        #line hidden
        
        #line 194 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 194 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Started(EventArgs e)\r\n\t    {\r\n\t       \tvar handler = ");

        
        #line default
        #line hidden
        
        #line 196 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 196 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Started;\r\n\t       \tif (handler != null) handler(this, e);\r\n\t    }\r\n\t\t\t\r\n\t\tprivate" +
        " void Invoke");

        
        #line default
        #line hidden
        
        #line 200 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 200 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Finished(EventArgs e)\r\n\t    {\r\n\t       \tvar handler = ");

        
        #line default
        #line hidden
        
        #line 202 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 202 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Finished;\r\n\t       \tif (handler != null) handler(this, e);\r\n\t    }\t\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 205 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				}
				
        
        #line default
        #line hidden
        
        #line 207 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\tprivate  ");

        
        #line default
        #line hidden
        
        #line 208 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(@interface.Name));

        
        #line default
        #line hidden
        
        #line 208 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 208 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 208 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n\t\t\t\r\n\t\tpublic ");

        
        #line default
        #line hidden
        
        #line 210 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(@interface.Name));

        
        #line default
        #line hidden
        
        #line 210 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 210 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));

        
        #line default
        #line hidden
        
        #line 210 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn ");

        
        #line default
        #line hidden
        
        #line 214 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 214 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n\t\t\t}\r\n\t\t\tset\r\n\t\t\t{\t\t\t\r\n\t\t\t\tif (");

        
        #line default
        #line hidden
        
        #line 218 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 218 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" != null) \r\n\t\t\t\t\tUnsubscribeTo");

        
        #line default
        #line hidden
        
        #line 219 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));

        
        #line default
        #line hidden
        
        #line 219 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("();\r\n\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 221 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 221 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" = value;\r\n\t\t\t\tSubscribeTo");

        
        #line default
        #line hidden
        
        #line 222 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));

        
        #line default
        #line hidden
        
        #line 222 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("();\r\n\t\t\t}\r\n\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 225 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				foreach (var evnt in @interface.AllEvents)
				{
					if (evnt.Name == "PropertyChanged")
					{

        
        #line default
        #line hidden
        
        #line 230 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\tprivate void On");

        
        #line default
        #line hidden
        
        #line 231 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.Name));

        
        #line default
        #line hidden
        
        #line 231 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Handler(object sender, PropertyChangedEventArgs e)\r\n\t\t{\r\n\t\t\tswitch (e.PropertyNam" +
        "e)\r\n\t\t\t{\r\n");

        
        #line default
        #line hidden
        
        #line 235 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

						foreach (var property in @interface.AllProperties)
						{

        
        #line default
        #line hidden
        
        #line 238 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t\t\tcase \"");

        
        #line default
        #line hidden
        
        #line 239 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 239 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\":\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tvar propClone = ");

        
        #line default
        #line hidden
        
        #line 241 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 241 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 241 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 241 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n\t\t\t\t\t\tif (");

        
        #line default
        #line hidden
        
        #line 242 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 242 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 242 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));

        
        #line default
        #line hidden
        
        #line 242 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" is ICloneable)\r\n\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\tpropClone = (");

        
        #line default
        #line hidden
        
        #line 244 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.Type));

        
        #line default
        #line hidden
        
        #line 244 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(")(propClone as ICloneable).Clone();\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t\tUpDispatcher.BeginInvoke(() =" +
        ">\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 248 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(property.GetDefaultPrivateFieldName()));

        
        #line default
        #line hidden
        
        #line 248 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" = propClone;\r\n\t\t\t\t\t\t\t\tvar handler = PropertyChanged;\r\n\t\t\t\t\t\t\t\tif (handler != nul" +
        "l) handler(this, new PropertyChangedEventArgs(e.PropertyName));\r\n\t\t\t\t\t\t\t});\r\n\r\n\t" +
        "\t\t\t\t\tbreak;\r\n\t\t\t\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 255 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

						}

        
        #line default
        #line hidden
        
        #line 257 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t\t\t\t\r\n\t\t\t}\r\n\t\t}\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 262 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

						
					}
					else
					{

        
        #line default
        #line hidden
        
        #line 267 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\tprivate void On");

        
        #line default
        #line hidden
        
        #line 268 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.Name));

        
        #line default
        #line hidden
        
        #line 268 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Handler(object sender, ");

        
        #line default
        #line hidden
        
        #line 268 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.GenericEventHandlerType));

        
        #line default
        #line hidden
        
        #line 268 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" e)\r\n\t\t{\r\n\t\t    var eventArgs = e;\r\n\t\t\tif (eventArgs is ICloneable)\r\n\t\t\t{\r\n\t\t\t\tev" +
        "entArgs = (");

        
        #line default
        #line hidden
        
        #line 273 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.GenericEventHandlerType));

        
        #line default
        #line hidden
        
        #line 273 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(")(eventArgs as ICloneable).Clone();\r\n\t\t\t}\r\n\t\t\tUpDispatcher.BeginInvoke(() =>\r\n\t\t\t" +
        "\t{\r\n\t\t\t\t\tvar handler = ");

        
        #line default
        #line hidden
        
        #line 277 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.Name));

        
        #line default
        #line hidden
        
        #line 277 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n\t\t\t\t\tif (handler != null) handler(this, eventArgs);\r\n\t\t\t\t});\r\n\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 281 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

					}
				}

        
        #line default
        #line hidden
        
        #line 284 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\tpublic void UnsubscribeTo");

        
        #line default
        #line hidden
        
        #line 285 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));

        
        #line default
        #line hidden
        
        #line 285 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("()\r\n\t\t{\r\n\t\t\tif (");

        
        #line default
        #line hidden
        
        #line 287 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 287 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" == null)\r\n\t\t\t\treturn;\r\n");

        
        #line default
        #line hidden
        
        #line 289 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				foreach (var evnt in @interface.AllEvents)
				{

        
        #line default
        #line hidden
        
        #line 292 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t\t");

        
        #line default
        #line hidden
        
        #line 293 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 293 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 293 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.Name));

        
        #line default
        #line hidden
        
        #line 293 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" -= On");

        
        #line default
        #line hidden
        
        #line 293 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.Name));

        
        #line default
        #line hidden
        
        #line 293 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Handler;\r\n");

        
        #line default
        #line hidden
        
        #line 294 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				}
		
        
        #line default
        #line hidden
        
        #line 296 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t}\t\t\r\n\r\n\t\tprivate void SubscribeTo");

        
        #line default
        #line hidden
        
        #line 299 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(propertyName));

        
        #line default
        #line hidden
        
        #line 299 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("()\r\n\t\t{\r\n");

        
        #line default
        #line hidden
        
        #line 301 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				foreach (var evnt in @interface.AllEvents)
				{

        
        #line default
        #line hidden
        
        #line 304 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t\t");

        
        #line default
        #line hidden
        
        #line 305 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 305 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 305 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.Name));

        
        #line default
        #line hidden
        
        #line 305 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" += On");

        
        #line default
        #line hidden
        
        #line 305 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(evnt.Name));

        
        #line default
        #line hidden
        
        #line 305 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Handler;\r\n");

        
        #line default
        #line hidden
        
        #line 306 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				}
		
        
        #line default
        #line hidden
        
        #line 308 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t}\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 311 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				foreach (var function in @interface.AllFunctions)
				{
				    if (function.Type == "void") 
					{
        
        #line default
        #line hidden
        
        #line 315 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 316 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Signature("", "BeginInvoke")));

        
        #line default
        #line hidden
        
        #line 316 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\r\n\t\t{\r\n\t\t\tDownDispatcher.BeginInvoke(() => \r\n\t\t\t\t{\r\n\t\t\t\t\tUpDispatcher.BeginInvoke" +
        "(() => Invoke");

        
        #line default
        #line hidden
        
        #line 320 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 320 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Started(EventArgs.Empty));\r\n\t\t\t\t\ttry\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 323 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 323 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 323 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.CallSignature("")));

        
        #line default
        #line hidden
        
        #line 323 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n\t\t\t\t\t}\r\n\t\t\t\t\tfinally\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tUpDispatcher.BeginInvoke(() => Invoke");

        
        #line default
        #line hidden
        
        #line 327 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 327 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Finished(EventArgs.Empty));\r\n\t\t\t\t\t}\r\n\t\t\t\t});\r\n\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 331 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
					}
				    if (function.Type != "void")
				    { 
        
        #line default
        #line hidden
        
        #line 333 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 334 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Type));

        
        #line default
        #line hidden
        
        #line 334 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 334 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 334 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Dummy;\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 335 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Signature("", "Invoke")));

        
        #line default
        #line hidden
        
        #line 335 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\r\n\t\t{\r\n\t\t\tvar result = ");

        
        #line default
        #line hidden
        
        #line 337 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 337 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Dummy;\r\n\t\t\tDownDispatcher.Invoke(() => \r\n\t\t\t\t{\r\n\t\t\t\t\tInvoke");

        
        #line default
        #line hidden
        
        #line 340 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 340 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Started(EventArgs.Empty);\r\n\t\t\t\t\ttry\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tresult = ");

        
        #line default
        #line hidden
        
        #line 343 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 343 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 343 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.CallSignature("")));

        
        #line default
        #line hidden
        
        #line 343 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n\t\t\t\t\t}\r\n\t\t\t\t\tfinally\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tInvoke");

        
        #line default
        #line hidden
        
        #line 347 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 347 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Finished(EventArgs.Empty);\r\n\t\t\t\t\t}\r\n\t\t\t\t});\r\n\t\t\treturn result;\r\n\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 352 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
					}
				    else
				    {
        
        #line default
        #line hidden
        
        #line 354 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 355 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Signature("", "Invoke")));

        
        #line default
        #line hidden
        
        #line 355 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\r\n\t\t{\r\n\t\t\t\r\n\t\t\tDownDispatcher.Invoke(() => \r\n\t\t\t\t{\r\n\t\t\t\t\tInvoke");

        
        #line default
        #line hidden
        
        #line 360 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 360 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Started(EventArgs.Empty);\r\n\t\t\t\t\ttry\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 363 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fieldName));

        
        #line default
        #line hidden
        
        #line 363 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 363 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.CallSignature("")));

        
        #line default
        #line hidden
        
        #line 363 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(";\r\n\t\t\t\t\t}\r\n\t\t\t\t\tfinally\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tInvoke");

        
        #line default
        #line hidden
        
        #line 367 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(function.Name));

        
        #line default
        #line hidden
        
        #line 367 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("Finished(EventArgs.Empty);\r\n\t\t\t\t\t}\r\n\t\t\t\t});\r\n\t\t}\r\n\t\t\t\t        \r\n");

        
        #line default
        #line hidden
        
        #line 372 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
				    }						
				}
        
        #line default
        #line hidden
        
        #line 373 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"
this.Write("\t}\r\n}\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 377 "C:\projects\CrossBase\CrossBase.CodeGeneration\Templates\DispatchProxyTemplate.tt"

				GenerateFooter();
				debugOutput += string.Format("Generated {0}\r\n", outputFileName);
				Delete(projectItem, outputFileName);
				Save(projectItem, outputFileName);
			}
		}
		base.Render();
	}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
